name: Draft release

on:
  push:
    branches: [main]

jobs:
  canary-release:
    name: Canary release
    runs-on: ubuntu-latest
    container: zaksabeast/devkitarm-rust
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add wasm target
        run: |
          rustup target add wasm32-unknown-unknown
          rustup component add clippy

      - name: Build
        run: make

      - name: Zip artifacts
        run: cd out && zip -r ../pnp.zip .

      - name: "Set build timestamp"
        run: echo "build_timestamp=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_OUTPUT
        id: build_timestamp

      - name: "Set tag name"
        run: echo "tag_name=canary-$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT
        id: tag_name

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: true
          tag_name: ${{ steps.tag_name.outputs.tag_name }}
          name: ${{ format('Canary {0}', steps.build_timestamp.outputs.build_timestamp) }}
          body: ${{ github.event.head_commit.message }}
          files: pnp.zip
