name: Draft release

on:
  workflow_dispatch:

jobs:
  draft-release:
    name: Draft release
    runs-on: ubuntu-latest
    container: zaksabeast/devkitarm-rust
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add wasm target
        run: |
          rustup target add wasm32-unknown-unknown
          rustup component add clippy

      - name: Build
        run: make

      - name: Zip artifacts
        run: cd out && zip -r ../pnp.zip .

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: pnp.zip
